version: "3.3"

volumes:
  db_volume:

services:
  shortener:
    build: .
    container_name: shortener_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: "postgres:14.5-alpine"
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: storageLinks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_volume:/var/lib/postgresql/data