version: '3.8'

services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener_app
    restart: no
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/storageLinks_db

  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=storageLinks_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    volumes:
      - shortener_db:/var/lib/postgresql/data
    restart: always

volumes:
  shortener_db: