spring:
  datasource:
    POSTGRES_DB: storageLinks_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true

servicePrefix: http://sh.l/